--donor table
-- CREATE TABLE Donor (
--     donor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     donor_name VARCHAR2(100),
--     gender CHAR(1),
--     age NUMBER,
--     blood_group VARCHAR2(3),
--     contact_phone VARCHAR2(15),
--     contact_email VARCHAR2(100),
--     donor_address VARCHAR2(255),
--     last_donation_date DATE
-- );

CREATE TABLE Donor (
    donor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_name VARCHAR2(15),
    date_of_birth DATE,
    gender CHAR(1),
    blood_group VARCHAR2(3),
    contact_phone VARCHAR2(15),
    contact_email VARCHAR2(15),
    -- street_address VARCHAR2(15),
    city VARCHAR2(20),
    -- state VARCHAR2(50),
    -- zip_code VARCHAR2(10),
    -- emergency_contact_name VARCHAR2(100),
    -- emergency_contact_relationship VARCHAR2(50),
    -- emergency_contact_phone VARCHAR2(15),
    -- medical_conditions VARCHAR2(255),
    last_donation_date DATE
    donor_username VARCHAR2(15)
    donor_password VARCHAR2(15)
);





--blood donation table
CREATE TABLE BloodDonation (
    donation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_id NUMBER,
    blood_group VARCHAR2(3),
    donation_date DATE,
    volume NUMBER, -- in mL
    CONSTRAINT fk_donor
        FOREIGN KEY (donor_id) 
        REFERENCES Donor(donor_id)
);

--inventory table, 1unit=500ml
CREATE TABLE BloodInventory (
    inventory_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blood_group VARCHAR2(3),
    units_available NUMBER,
    expiry_date DATE
);

--hospital table
-- CREATE TABLE Hospital (
--     hospital_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     hospital_name VARCHAR2(100),
--     password VARCHAR2(100),
--     hospital_address VARCHAR2(255),
--     contact_phone VARCHAR2(15),
--     contact_email VARCHAR2(100)
-- );

CREATE TABLE Hospital (
    hospital_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_name VARCHAR2(15),
    -- registration_number VARCHAR2(50),
    hospital_address VARCHAR2(20),
    city VARCHAR2(15),
    -- state VARCHAR2(50),
    -- postal_code VARCHAR2(10),
    -- contact_person_name VARCHAR2(100),
    -- contact_person_designation VARCHAR2(50),
    hospital_phone VARCHAR2(15),
    -- contact_person_mobile VARCHAR2(15),
    contact_email VARCHAR2(15),
    hospital_username VARCHAR2(15)
    hospital_password VARCHAR2(15)
);



--request table , 'Y' for yes, 'N' for no
CREATE TABLE BloodRequest (
    request_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hospital_id NUMBER,
    blood_group VARCHAR2(3),
    units_requested NUMBER,
    request_date DATE,
    fulfilled CHAR(1) DEFAULT 'N', 
    CONSTRAINT fk_hospital
        FOREIGN KEY (hospital_id) 
        REFERENCES Hospital(hospital_id)
);
